stages:
    - build
    - test
    - security
    - publish
    - prepare
    - release
    - deploy

variables:
    DOTNET_VERSION: "8.0"


# When Merge Request is opened

build_job:
    stage: build
    image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
    script:
        - echo "Building project..."
        - dotnet build
    artifacts: # Preserve build outputs for future use
        paths:
            - bin/
        expire_in: 1 week
    resource_group: common
    rules:
        - if: '$CI_MERGE_REQUEST_ID'

test_job:
    stage: test
    image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
    services:
        # DinD service is required for Testcontainers
        - name: docker:dind
          command: ["--tls=false"]
    variables:
        # Set environment to Staging, so that Testcontainers will be used
        ASPNETCORE_ENVIRONMENT: "Staging"
        # Instruct Docker to use the DinD daemon
        DOCKER_HOST: "tcp://docker:2375"
        # Instruct Docker not to start over TLS
        DOCKER_TLS_CERTDIR: ""
        # Improve performance with overlayfs
        DOCKER_DRIVER: overlay2
    script:
        - echo "Running test suite..."
        - dotnet test --logger "console;verbosity=normal" --logger "trx"
    artifacts:
        when: always
        reports:
            junit: TestResults/*.trx
        expire_in: 1 month
    dependencies:
        - build_job # test_job depends on artifacts produced by build_job (avoids rebuilding the project)
    resource_group: common
    rules:
        - if: '$CI_MERGE_REQUEST_ID'

# This doesn't cause the pipeline to fail if a vulnerability is found, but vulnerabilities do get printed
dependency_scanning:
    stage: security
    image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
    script:
        - echo "Running dependency scanning..."
        - dotnet restore
        - dotnet list package --vulnerable
    resource_group: common
    rules:
        - if: '$CI_MERGE_REQUEST_ID'



# When a merge is made into dev

publish_job:
    only:
        - main
    stage: publish
    image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
    script:
        - dotnet publish Bookworms-Server -c Release -o out
    artifacts:
        paths:
            - out/
        expire_in: 1 week
    resource_group: common

prepare_job:
    only:
        - main
    stage: prepare
    image: alpine:latest
    before_script:
        - apk add --no-cache git
    script:
        |
        START_DATE="2025-01-09"
        CURRENT_DATE=$(date +%Y-%m-%d)
        SECONDS_DIFF=$(( $(date -d "$CURRENT_DATE" +%s) - $(date -d "$START_DATE" +%s) ))
        WEEK_NUMBER=$(( SECONDS_DIFF / 604800 + 1 ))
        MARCH_10TH="2025-03-10"
        MARCH_17TH="2025-03-17"
        if [ $(date -d "$CURRENT_DATE" +%s) -ge $(date -d "$MARCH_10TH" +%s) ] && [ $(date -d "$CURRENT_DATE" +%s) -lt $(date -d "$MARCH_17TH" +%s) ]; then
            WEEK_NUMBER="9A"
        elif [ $(date -d "$CURRENT_DATE" +%s) -ge $(date -d "$MARCH_17TH" +%s) ]; then
            WEEK_NUMBER=$(( WEEK_NUMBER + 1 ))
        fi
        LATEST_TAG=$(git tag -l "v0.$WEEK_NUMBER.*" | sort -V | tail -n 1)
        if [ -z "$LATEST_TAG" ]; then
            HOTFIX_NUMBER=0
        else
            HOTFIX_NUMBER=$(( ${LATEST_TAG##*.} + 1 ))
        fi
        RELEASE_TAG="v0.$WEEK_NUMBER.$HOTFIX_NUMBER"
        echo "TAG=$RELEASE_TAG" >> variables.env
    artifacts:
        reports:
            dotenv: variables.env
    resource_group: common

release_job:
    only:
        - main
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    dependencies:
        - publish_job
        - prepare_job
    script:
        - echo "Creating GitLab release with tag $TAG"
    release:
        name: "Release $TAG"
        description: "Created using the release CLI"
        tag_name: "$TAG"
        ref: "$CI_COMMIT_SHA"
    resource_group: common

deploy_job:
    only:
        - main
    stage: deploy
    image: alpine:latest
    dependencies:
        - publish_job
    before_script:
        # Install open-ssh client
        - apk add --no-cache openssh-client
        # Start ssh-agent
        - eval $(ssh-agent -s)
        # Add the private key to ssh-agent
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -q -
    script:
        # Replace the build artifacts in the EC2 instance, and restart the server
        - ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'systemctl stop bookworms.service'
        - ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'rm -rf $DEPLOYMENT_DIR/*'
        - scp -r -C out/* $EC2_USER@$EC2_HOST:$DEPLOYMENT_DIR
        - ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'systemctl start bookworms.service'
    variables:
        # Don't pull the repository for this job
        GIT_STRATEGY: none
        DEPLOYMENT_DIR: /var/www/api/
    resource_group: common
