// <auto-generated />
using System;
using BookwormsServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookwormsServer.Migrations
{
    [DbContext(typeof(BookwormsDbContext))]
    partial class BookwormsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BookBookshelf", b =>
                {
                    b.Property<string>("BooksBookId")
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("BookshelvesBookshelfId")
                        .HasColumnType("char(36)");

                    b.HasKey("BooksBookId", "BookshelvesBookshelfId");

                    b.HasIndex("BookshelvesBookshelfId");

                    b.ToTable("BookBookshelf");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Book", b =>
                {
                    b.Property<string>("BookId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Isbn10")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Isbn13")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Level")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<double?>("StarRating")
                        .HasColumnType("double");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("BookId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Bookshelf", b =>
                {
                    b.Property<Guid>("BookshelfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("BookshelfId");

                    b.ToTable("Bookshelves");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.BookshelfBook", b =>
                {
                    b.Property<Guid>("BookshelfId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BookId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("BookshelfId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BookshelfBooks");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Child", b =>
                {
                    b.Property<Guid>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClassroomCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ParentUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ReadingLevel")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("ChildId");

                    b.HasIndex("ClassroomCode");

                    b.HasIndex("ParentUsername");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Classroom", b =>
                {
                    b.Property<string>("ClassroomCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("ClassroomName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("ClassroomCode");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<double>("StarRating")
                        .HasColumnType("double");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("ReviewId");

                    b.HasIndex("Username");

                    b.HasIndex("BookId", "Username")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("UserIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Username");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.ChildBookshelf", b =>
                {
                    b.HasBaseType("BookwormsServer.Models.Entities.Bookshelf");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ChildId");

                    b.HasIndex("ChildId");

                    b.ToTable("ChildBookshelves");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.ClassroomBookshelf", b =>
                {
                    b.HasBaseType("BookwormsServer.Models.Entities.Bookshelf");

                    b.Property<string>("ClassroomCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasIndex("ClassroomCode");

                    b.ToTable("ClassroomBookshelves");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.CompletedBookshelf", b =>
                {
                    b.HasBaseType("BookwormsServer.Models.Entities.Bookshelf");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ChildId");

                    b.HasIndex("ChildId")
                        .IsUnique();

                    b.ToTable("CompletedBookshelves");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.InProgressBookshelf", b =>
                {
                    b.HasBaseType("BookwormsServer.Models.Entities.Bookshelf");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ChildId");

                    b.HasIndex("ChildId")
                        .IsUnique();

                    b.ToTable("InProgressBookshelves");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Parent", b =>
                {
                    b.HasBaseType("BookwormsServer.Models.Entities.User");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("Parent");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Teacher", b =>
                {
                    b.HasBaseType("BookwormsServer.Models.Entities.User");

                    b.Property<string>("ClassroomCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasIndex("ClassroomCode")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("BookBookshelf", b =>
                {
                    b.HasOne("BookwormsServer.Models.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookwormsServer.Models.Entities.Bookshelf", null)
                        .WithMany()
                        .HasForeignKey("BookshelvesBookshelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.BookshelfBook", b =>
                {
                    b.HasOne("BookwormsServer.Models.Entities.Book", "Book")
                        .WithMany("BookshelfBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookwormsServer.Models.Entities.Bookshelf", "Bookshelf")
                        .WithMany("BookshelfBooks")
                        .HasForeignKey("BookshelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Bookshelf");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Child", b =>
                {
                    b.HasOne("BookwormsServer.Models.Entities.Classroom", "Classroom")
                        .WithMany("Children")
                        .HasForeignKey("ClassroomCode");

                    b.HasOne("BookwormsServer.Models.Entities.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Review", b =>
                {
                    b.HasOne("BookwormsServer.Models.Entities.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookwormsServer.Models.Entities.User", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.ChildBookshelf", b =>
                {
                    b.HasOne("BookwormsServer.Models.Entities.Bookshelf", null)
                        .WithOne()
                        .HasForeignKey("BookwormsServer.Models.Entities.ChildBookshelf", "BookshelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookwormsServer.Models.Entities.Child", "Child")
                        .WithMany("Bookshelves")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.ClassroomBookshelf", b =>
                {
                    b.HasOne("BookwormsServer.Models.Entities.Bookshelf", null)
                        .WithOne()
                        .HasForeignKey("BookwormsServer.Models.Entities.ClassroomBookshelf", "BookshelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookwormsServer.Models.Entities.Classroom", "Classroom")
                        .WithMany("Bookshelves")
                        .HasForeignKey("ClassroomCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.CompletedBookshelf", b =>
                {
                    b.HasOne("BookwormsServer.Models.Entities.Bookshelf", null)
                        .WithOne()
                        .HasForeignKey("BookwormsServer.Models.Entities.CompletedBookshelf", "BookshelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookwormsServer.Models.Entities.Child", "Child")
                        .WithOne("Completed")
                        .HasForeignKey("BookwormsServer.Models.Entities.CompletedBookshelf", "ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.InProgressBookshelf", b =>
                {
                    b.HasOne("BookwormsServer.Models.Entities.Bookshelf", null)
                        .WithOne()
                        .HasForeignKey("BookwormsServer.Models.Entities.InProgressBookshelf", "BookshelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookwormsServer.Models.Entities.Child", "Child")
                        .WithOne("InProgress")
                        .HasForeignKey("BookwormsServer.Models.Entities.InProgressBookshelf", "ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Teacher", b =>
                {
                    b.HasOne("BookwormsServer.Models.Entities.Classroom", "Classroom")
                        .WithOne("Teacher")
                        .HasForeignKey("BookwormsServer.Models.Entities.Teacher", "ClassroomCode");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Book", b =>
                {
                    b.Navigation("BookshelfBooks");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Bookshelf", b =>
                {
                    b.Navigation("BookshelfBooks");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Child", b =>
                {
                    b.Navigation("Bookshelves");

                    b.Navigation("Completed");

                    b.Navigation("InProgress");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Classroom", b =>
                {
                    b.Navigation("Bookshelves");

                    b.Navigation("Children");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.User", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BookwormsServer.Models.Entities.Parent", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
